import {
  borderBottomDark,
  darkBackground,
  darkSecondaryBackground,
  eighthCardDark,
  fifthCardDark,
  firstCardDark,
  fourthCardDark,
  ninthCardDark,
  searchDark,
  searchFocusDark,
  secondCardDark,
  seventhCardDark,
  sixthCardDark,
  tenthCardDark,
  textCardDark,
  textDark,
  textDarkSecondary,
  textGrayDark,
  thirdCardDark,
  unLocalizationDark,
} from "./variableColors";

export const darkTheme = {
  name: "dark",
  colors: {
    primary: darkBackground,
    secondary: darkSecondaryBackground,
    borderBottomTab: borderBottomDark,
    unLocalization: unLocalizationDark,
    text: textDark,
    textSecondary: textDarkSecondary,
    textGray: textGrayDark,
    textCard: textCardDark,
    search: searchDark,
    searchFocus: searchFocusDark,
    cards: {
      firstCard: firstCardDark,
      secondCard: secondCardDark,
      thirdCard: thirdCardDark,
      fourthCard: fourthCardDark,
      fifthCard: fifthCardDark,
      sixthCard: sixthCardDark,
      seventhCard: seventhCardDark,
      eighthCard: eighthCardDark,
      ninthCard: ninthCardDark,
      tenthCard: tenthCardDark,
    },
  },
};
