import {
  borderBottomLight,
  eighthCard,
  fifthCard,
  firstCard,
  fourthCard,
  lightBackground,
  lightSecondaryBackground,
  ninthCard,
  searchFocusLight,
  searchLight,
  secondCard,
  seventhCard,
  sixthCard,
  tenthCard,
  textCard,
  textGrayLight,
  textLight,
  textLightSecondary,
  thirdCard,
  unLocalization,
} from "./variableColors";

export const lightTheme = {
  name: "light",
  colors: {
    primary: lightBackground,
    secondary: lightSecondaryBackground,
    borderBottomTab: borderBottomLight,
    unLocalization: unLocalization,
    text: textLight,
    textSecondary: textLightSecondary,
    textGray: textGrayLight,
    textCard: textCard,
    search: searchLight,
    searchFocus: searchFocusLight,
    cards: {
      firstCard: firstCard,
      secondCard: secondCard,
      thirdCard: thirdCard,
      fourthCard: fourthCard,
      fifthCard: fifthCard,
      sixthCard: sixthCard,
      seventhCard: seventhCard,
      eighthCard: eighthCard,
      ninthCard: ninthCard,
      tenthCard: tenthCard,
    },
  },
};
