import logoHeader from "../svg/svgs/logoHeader.svg";
import houseIcon from "../svg/svgs/houseIcon.svg";
import houseIconDark from "../svg/svgs/houseIconDark.svg";
import themeDark from "../svg/svgs/themeDark.svg";
import themeLight from "../svg/svgs/themeLight.svg";
import unDots from "../svg/svgs/un-dots.svg";
import searchIcon from "../svg/svgs/searchLight.svg";
import searchDarkIcon from "../svg/svgs/searchDark.svg";
import logoChat from "../svg/svgs/logoChat.svg";
import well from "../svg/svgs/whell.svg";

export const logoHeaderSvg = logoHeader;
export const houseIconSvg = houseIcon;
export const houseIconDarkSvg = houseIconDark;
export const iconThemeDark = themeDark;
export const iconThemeLight = themeLight;
export const unDotsIcon = unDots;
export const searchIconLight = searchIcon;
export const searchIconDark = searchDarkIcon;
export const logoIconChat = logoChat;
export const wellIcon = well;
